version: '1.0'
coder:
    exampleDir: ~
    # Replace Example Dir wit relative path e.g. ./examples/ to benefit from brixcoder code completion
    include:
        - ./src/
        - ./.brix-job/
    exclude:
        - ./vendor/
        - ./node_modules
