# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100"

command:


  run:


  dev:
    - "D:webpack build --watch"

  init-workspaces:
    - "mkdir -p workspaces"
    - "git -C ./workspaces/ clone git@github.com:kasimirjs/kasi-core.git"
    - "npm install"

  update:
    - "npm update"
    - "webpack build"

  killall:
    - killall jekyll
